name: Example Workflow

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run your custom action (version 1.0.0)
        uses: polatengin/repo_TO_BE_DELETED@v1.0.0
        with:
          name: 'Engin'
